### ISSUE TITLE
Have you checked if it can be fixed?

### ISSUE THREAD

**Issue by uNderdog101** [Karunamon/muda#13]
Sorry about making this thread, but github doesn't have a messaging feature and I think sending you an email would be a bit too forward of me.

It's been three weeks since I first asked, have you taken a look to see if it can be fixed? I could really use it if it worked.

Thanks in advance.

**Comment by ctrlcctrlv** [comment]
Spamming issues does nothing. Please stop. Maybe he no longer cares about this project, or has no time because of a real life job. Open source developers are not beholden to your whims that they do some free work.

Either learn to code or pay someone to fix it, but quit spamming issues.

**Comment by Karunamon** [comment]
Gotta go with @ctrlcctrlv here - please don't create new issues just to get my attention, I get emails whenever comments are added to already open tickets anyways.
