### ISSUE TITLE
Muda is a pain to install

### ISSUE THREAD

**Issue by Karunamon** [Karunamon/muda#4]
It's Ruby, which requires the user to have a separate runtime installed, and probably yet another separate runtime to install should this tool ever grow a GUI.

Ideally: Come up with an automated way to package Muda as a one-click operation with some kind of update mechanism.

**Comment by ericfariase** [comment]
Yes, please!

**Comment by Karunamon** [comment]
Calling this fixed with the rewrite - all dependencies now included in one jar file, only requirement for the user now is having Java 7 or 8 laying around.
