### ISSUE TITLE
Having problems with the installation

### ISSUE THREAD

**Issue by ericfariase** [Karunamon/muda#8]
When I type "./muda.rb -h", I get this:

"read 1810030 –directory /media/Backup/Imagens/Spurdo
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file – mechanize (LoadError)
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from ./muda.rb:2:in `<main>'"

Help, please!
![captura de tela - 23-04-2015 - 09 43 44](https://cloud.githubusercontent.com/assets/12084325/7297223/42313792-e99d-11e4-9f0e-755fe52668a8.png)

**Comment by Karunamon** [comment]
Hi Eric,

I noticed your ruby version is 1.9.1 - this will not work for Muda. It must be at least 2.1.5.

Simplest thing you could do here unless you want to mess around with your OS's packages (not recommended) is to install [Rbenv](https://github.com/sstephenson/rbenv#basic-github-checkout) and its associated ruby-build plugin (it's simple, just a couple of git clones and two lines in your bash_profile). Once that's done, you should be able to do something similar to this:

```sh
rbenv install 2.1.5
cd muda
rbenv local 2.1.5
gem install bundler
bundle install
muda -h
```

If any of that fails, make sure your distro's software development tools are installed. (Debian calls this build-essential, Rhellikes call it the "Development Tools" group)

**Comment by ericfariase** [comment]
When i type rbenv install 2.1.5 I just get this: eric@Eric:~$ rbenv install 2.1.5
ruby-build: definition not found: 2.1.5

**Comment by ericfariase** [comment]
Also,

eric@Eric:~/.rbenv$ cd
eric@Eric:~$ rbenv install 2.1.5
ruby-build: definition not found: 2.1.5
eric@Eric:~$ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
eric@Eric:~$ sudo gem install bundler
Successfully installed bundler-1.9.4
1 gem installed
Installing ri documentation for bundler-1.9.4...
unable to convert U+2015 from UTF-8 to US-ASCII for lib/bundler/friendly_errors.rb, skipping
Installing RDoc documentation for bundler-1.9.4...
unable to convert U+2015 from UTF-8 to US-ASCII for lib/bundler/friendly_errors.rb, skipping
eric@Eric:~$ bundle install
Could not locate Gemfile or .bundle/ directory

**Comment by ericfariase** [comment]
Now when I try to update, i get this:
eric@Eric:~$ rbenv install 2.1.5
rbenv: no such command `install'

**Comment by ericfariase** [comment]
Trying with sudo: 
eric@Eric:~$ sudo rbenv install 2.1.5
[sudo] password for eric: 
ruby-build: definition not found: 2.1.5
eric@Eric:~$

**Comment by Karunamon** [comment]
You shouldn't have to use sudo for any of this, something is very wrong. When you did the rbenv and ruby-build git clones, did you do it using your account in your home directory?

**Comment by ericfariase** [comment]
Yes. OK.

**Comment by Karunamon** [comment]
Hi again,

Could you try the latest release if you happen to have Java kicking around? You should find it a bit easier to use :)

**Comment by Karunamon** [comment]
Going to close this since I haven't heard from you in a while - please feel free to reopen if you're still having difficulties with the new Java version :)

**Comment by ericfariase** [comment]
I just gave up. I'm using #!++ and still can't update the ruby. Thanks for the support. 

Enviado do Yahoo Mail no Android

De:"Michael Parks" <notifications@github.com>
Data:14:37 seg, 8 de jun de PM
Assunto:Re: [muda] Having problems with the installation (#8)

Going to close this since I haven't heard from you in a while - please feel free to reopen if you're still having difficulties with the new Java version :)

**Comment by Karunamon** [comment]
Did you try the new Java release? The rewrite was, in part, so the messing
around with Ruby was no longer necessary.

**Comment by ericfariase** [comment]
I didn't know that there was a new release. Where can I get it?

Enviado do Yahoo Mail no Android

De:"Michael Parks" <notifications@github.com>
Data:15:14 seg, 8 de jun de PM
Assunto:Re: [muda] Having problems with the installation (#8)

Did you try the new Java release? The rewrite was, in part, so the messing
around with Ruby was no longer necessary.
